### ISSUE TITLE
Support event encoders and decoders for all event types available in the Falco libs

### ISSUE THREAD

**Issue by jasondellaluce** [falcosecurity/plugin-sdk-cpp#33]
**Motivation**

The SDK provides encoders and decoders for only `PPME_ASYNCEVENT_E` and `PPME_PLUGINEVENT_E`. As the SDK practially allows working with every event supported in `falcosecurity/libs`, we should introduce opt-in headers with encoders and decoders for all of them.

**Comment by h4l0gen** [comment]
Hey @jasondellaluce i am interested in this issue. If this issue is still open can you tell me more about it

**Comment by jasondellaluce** [comment]
Hi @h4l0gen. In the current state of the SDK we provide encoders and decoders only for `PPME_ASYNCEVENT_E` and `PPME_PLUGINEVENR_E` event types, however the falcosecurity/libs support many more. The goal of this issue is to track the effort of supporting all event types. Here's the full list I'm referring to, with schemas for all events.

**Comment by h4l0gen** [comment]
@jasondellaluce please provide list and schema for all events.

**Comment by h4l0gen** [comment]
/remove-lifecycle stale 
Just sleep from my mind, working on it.
